# 简化水库控制示例配置文件
# 传统配置文件模式

simulation:
  duration: 200
  dt: 1.0
  solver: 'euler'

components:
  reservoir_1:
    class: Reservoir
    inflow_topic: inflow/reservoir_1
    initial_state:
      volume: 10.0
      water_level: 5.0
    parameters:
      outlet_coeff: 0.6
      surface_area: 2.0
      
  gate_1:
    class: Gate
    control_topic: control/gate_1
    initial_state:
      opening: 0.5
    parameters:
      max_opening: 1.0
      discharge_coeff: 0.8
      gate_width: 2.0

connections:
  - from: reservoir_1
    to: gate_1
    type: outlet

control:
  pid_controller:
    target_variable: reservoir_1.water_level
    control_variable: gate_1.opening
    setpoint: 8.0
    kp: 0.5
    ki: 0.1
    kd: 0.05
    output_limits: [0.0, 1.0]
    anti_windup: true

inflow:
  reservoir_1:
    type: step
    value: 5.0
    start_time: 50
    end_time: 150

output:
  variables:
    - reservoir_1.water_level
    - reservoir_1.volume
    - gate_1.opening
    - gate_1.outflow
  save_to_file: true
  plot: true