# 简化水库控制示例 - 通用配置文件
metadata:
  name: "简化水库控制示例"
  description: "使用通用工具库构建的水库PID控制系统"
  version: "1.0"
  category: "demo"
  author: "CHS-SDK Team"
  tags: ["reservoir", "control", "pid", "demo"]

simulation:
  duration: 200
  dt: 1.0
  start_time: 0
  end_time: 200
  solver: "euler"
  
components:
  - class: Reservoir
    id: reservoir_1
    inflow_topic: inflow/reservoir_1
    initial_state:
      volume: 10.0
      water_level: 5.0
    parameters:
      outlet_coeff: 0.6
      surface_area: 2.0
      min_level: 0.0
      max_level: 10.0
      
  - class: Gate
    id: gate_1
    control_topic: control/gate_1
    initial_state:
      opening: 0.5
    parameters:
      max_opening: 1.0
      discharge_coeff: 0.8
      gate_width: 2.0
      response_time: 0.1

connections:
  - from: reservoir_1
    to: gate_1
    type: outlet
    parameters:
      pipe_length: 10.0
      pipe_diameter: 1.0

agents:
  - class: PIDControlAgent
    id: pid_controller
    observation_topic: state/reservoir_1
    action_topic: control/gate_1
    parameters:
      kp: 0.5
      ki: 0.1
      kd: 0.05
      setpoint: 6.0
      output_limits: [0.0, 1.0]
      integral_limits: [-1.0, 1.0]
      derivative_filter: 0.1

  - class: DisturbanceAgent
    id: inflow_disturbance
    action_topic: inflow/reservoir_1
    parameters:
      pattern: "step"
      values: [5.0, 8.0, 3.0]
      times: [0, 50, 150]

output:
  show_progress: true
  show_final_summary: true
  log_level: "INFO"
  save_history: true
  export_format: ["csv", "json"]
  plot_results: true
  
visualization:
  enabled: true
  real_time: false
  save_plots: true
  plot_types: ["time_series", "phase_portrait"]
  
performance:
  metrics: ["settling_time", "overshoot", "steady_state_error"]
  analysis_enabled: true