# 控制与智能体示例 - 统一配置文件
metadata:
  name: "控制与智能体系统"
  description: "展示数字孪生智能体、本地控制智能体和PID控制器的集成应用"
  version: "1.0"
  category: "notebooks"

simulation:
  duration: 200
  dt: 0.5
  
components:
  - class: Reservoir
    id: controlled_reservoir
    inflow_topic: inflow/controlled_reservoir
    initial_state:
      volume: 15.0
      water_level: 7.5
    parameters:
      surface_area: 2.0
      outlet_coeff: 0.65
      
  - class: Gate
    id: control_gate
    control_topic: control/control_gate
    initial_state:
      opening: 0.4
    parameters:
      max_opening: 1.0
      discharge_coeff: 0.85
      gate_width: 1.8
      
  - class: Pump
    id: inflow_pump
    control_topic: control/inflow_pump
    initial_state:
      flow_rate: 3.0
    parameters:
      max_flow_rate: 10.0
      efficiency: 0.85
      power_rating: 5.0

connections:
  - from: inflow_pump
    to: controlled_reservoir
    type: inflow
  - from: controlled_reservoir
    to: control_gate
    type: outlet

agents:
  - class: DigitalTwinAgent
    id: reservoir_twin
    observation_topic: state/controlled_reservoir
    parameters:
      update_frequency: 2.0
      state_variables: ["water_level", "volume", "outflow"]
      
  - class: LocalControlAgent
    id: gate_controller
    observation_topic: state/controlled_reservoir
    action_topic: control/control_gate
    parameters:
      control_type: "pid"
      setpoint: 8.0
      kp: 0.6
      ki: 0.15
      kd: 0.08
      output_limits: [0.0, 1.0]
      
  - class: PIDController
    id: pump_controller
    observation_topic: state/controlled_reservoir
    action_topic: control/inflow_pump
    parameters:
      setpoint: 7.5
      kp: 2.0
      ki: 0.5
      kd: 0.2
      output_limits: [0.0, 10.0]
      
  - class: DisturbanceAgent
    id: demand_disturbance
    action_topic: demand/controlled_reservoir
    parameters:
      pattern: "step_sequence"
      values: [2.0, 5.0, 1.5, 4.0]
      times: [0, 50, 100, 150]
      
  - class: MonitoringAgent
    id: system_monitor
    observation_topics:
      - state/controlled_reservoir
      - state/control_gate
      - state/inflow_pump
    parameters:
      monitoring_interval: 5.0
      alert_levels:
        water_level: {min: 2.0, max: 12.0}
        gate_opening: {min: 0.0, max: 1.0}

output:
  show_progress: true
  show_final_summary: true
  log_level: "INFO"
  save_history: true